# Generated by Django 5.2.6 on 2025-09-08 17:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_certificate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='certificate',
            old_name='organization',
            new_name='issuer',
        ),
        migrations.RemoveField(
            model_name='certificate',
            name='issue_date',
        ),
        migrations.AddField(
            model_name='certificate',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='certificate',
            name='certificate_file',
            field=models.FileField(default='', upload_to='certificates/'),
            preserve_default=False,
        ),
    ]
