# Generated by Django 5.2.6 on 2025-09-08 19:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_joblisting'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField(help_text='The text of the interview question.')),
                ('answer_text', models.TextField(help_text='A detailed answer to the question.')),
                ('difficulty', models.CharField(choices=[('Easy', 'Easy'), ('Medium', 'Medium'), ('Hard', 'Hard')], default='Medium', max_length=20)),
                ('skill', models.ForeignKey(help_text='The skill this question relates to.', on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='api.skill')),
            ],
            options={
                'ordering': ['skill', 'difficulty'],
            },
        ),
    ]
