# Generated by Django 5.2.6 on 2025-09-09 08:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interviewquestion',
            name='answer_text',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='interviewquestion',
            name='question_text',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='interviewquestion',
            name='skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='api.skill'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='face_encoding',
            field=models.TextField(blank=True, null=True),
        ),
    ]
